### ISSUE TITLE
An example to predict probabilities for a given image

### ISSUE THREAD

**Issue by blazespinnaker** [lim0606/caffe-googlenet-bn#3]
Hi, I looked through this and it looks pretty great, though the test_bn and predict_bn have thrown me for a bit of a loop.  I was able to get it to build and run on an AWS GPU large but I'm having troubles figuring out the right command line inputs to use for predicting probabilities on images I have.

Any examples or hints you can provide would be great, thx!

**Comment by lim0606** [comment]
@blazespinnaker 

Sorry for late response. 

Please see following link, https://github.com/lim0606/caffe-fast-rcnn/tree/fast-rcnn-cleanup/models/jhlim_inception_bn

The updated bn layer and etc's in this repo work with recent caffe versions, including the layers with cuDNN v3.
